---
application:
  name: "Automation Exercise"
  url: "https://automationexercise.com/"

users:
  - type: "admin"
    name: "Ahmet"
    username: "atezgider@gmail.com"
    password: "atezgider"
  - type: "tester"
    name: "Ahmet"
    username: "atezgider@gmail.com"
    password: "atezgider"
  - type: "user"
    name: "Ahmet"
    username: "atezgider@gmail.com"
    password: "atezgider"


tests:
  browser: CHROME # CHROME, FIREFOX, EDGE, SAFARI
  features: "src/main/resources/features/01Login.feature"
  tags: "@aaaa"
  dryRun: false



chrome:
  version: 116
  extensions:
    #- "crx/add_blocker_extension_4_44_0_0.crx"
    - ""
  options:
    - "--start-maximized"
    #- "--disable-popup-blocking"
    #- "--headless"
    #- "--incognito"
    - "user-data-dir=C:/browserProfile/chrome"

edge:
  version: 110
  extensions:
    - "crx/add_blocker_extension_4_44_0_0.crx"
    - ""
  options:
    - ""
    - ""

firefox:
  version: 62
  extensions:
    - ""
  options:
    - "-private"
    - ""

variables:
  var1: "variable1"
  var2: "variable2"
  var3: "variable3"
  var4: "variable4"
  aaa: "bbbbbb"
  ali.veli.deli: "121312312312"