---
application:
  name: "Automation Exercise"
  url: "https://automationexercise.com/"

users:
  - type: "admin"
    name: "Ahmet"
    username: "atezgider@gmail.com"
    password: "ahmet123"
  - type: "tester"
    name: "Ahmet"
    username: "atezgider@gmail.com"
    password: "ahmet123"
  - type: "user"
    name: "Ahmet"
    username: "atezgider@gmail.com"
    password: "ahmet123"


tests:
  browser: CHROME # FIREFOX, EDGE, SAFARI
  features: "c:/features"
  tags: ""


chrome:
  version: 116
  options:
    - "--start-maximized"
    #- "--headless"
    #- "--incognito"
    #- "user-data-dir=C:/Users/pc/AppData/Local/Google/Chrome/User Data"

edge:
  version: 110
  options:
    - ""
    - ""

firefox:
  version: 62
  options:
    - ""
    - ""

variables:
  var1: "variable1"
  var2: "variable2"
  var3: "variable3"
  var4: "variable4"
  aaa: "bbbbbb"
  ali.veli.deli: "121312312312"